import Head from "next/head";

import Hero from "@/modules/Home/Hero/Hero";
import Container from "@/UI-Kit/Container/Container";

import PopularMovies from "@/modules/Home/PopularMovies/PopularMovies";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <Hero />
        <PopularMovies />
      </Container>
    </>
  );
}
